### ISSUE TITLE
Cannot connect to the websocket server - ERROR TS2345 

### ISSUE THREAD

**Issue by Vermintin** [metafetish/buttplug-playground#1]
Hi, 
Great project but I can't get it working out of the box, it's frustrating
The documentation should state which version of Nodejs is required and how to launch it from scratch.

My env :
Buttplug Playground Version 20170925
Node : 8.9.0 (nvm) x64
Env : Windows 10x64
I am using the c# websocket server and it's working with other haptic projects

I did :  
npm install
npm run start

The browser is launched and the GUI is displayed. When i hit the connect button, nothing happen.
I've joined the logs.
My guess is it's working for your env. Again please let us know what this env is in the doc.
Best Regards

---------------------------------------------
 [tsl] ERROR in ***********\buttplug-playground-master\src\components\VibrationComponent\VibrationComponent.ts(6,2)
      TS2345: Argument of type 'typeof VibrationComponent' is not assignable to parameter of type 'VueClass<Vue>'.
  Type 'typeof VibrationComponent' is not assignable to type 'new (...args: any[]) => Vue'.
    Type 'VibrationComponent' is not assignable to type 'Vue'.
      Types of property '$options' are incompatible.
        Type 'ComponentOptions<VibrationComponent, DefaultData<VibrationComponent>, DefaultMethods<VibrationCom...' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.
          Type 'VibrationComponent' is not assignable to type 'Vue'.

 [tsl] ERROR in **************\buttplug-playground-master\src\components\RotationComponent\RotationComponent.ts(6,2)
      TS2345: Argument of type 'typeof RotationComponent' is not assignable to parameter of type 'VueClass<Vue>'.
  Type 'typeof RotationComponent' is not assignable to type 'new (...args: any[]) => Vue'.
    Type 'RotationComponent' is not assignable to type 'Vue'.
      Types of property '$options' are incompatible.
        Type 'ComponentOptions<RotationComponent, DefaultData<RotationComponent>, DefaultMethods<RotationCompon...' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.
          Type 'RotationComponent' is not assignable to type 'Vue'.

ERROR in ./node_modules/ts-loader!./src/components/PositionComponent/PositionComponent.ts
[tsl] ERROR in **********\buttplug-playground-master\src\components\PositionComponent\PositionComponent.ts(6,2)
      TS2345: Argument of type 'typeof PositionComponent' is not assignable to parameter of type 'VueClass<Vue>'.
  Type 'typeof PositionComponent' is not assignable to type 'new (...args: any[]) => Vue'.
    Type 'PositionComponent' is not assignable to type 'Vue'.
      Types of property '$options' are incompatible.
        Type 'ComponentOptions<PositionComponent, DefaultData<PositionComponent>, DefaultMethods<PositionCompon...' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.
          Type 'PositionComponent' is not assignable to type 'Vue'.

ERROR in ./node_modules/ts-loader!./src/App.ts
[tsl] ERROR in **********\buttplug-playground-master\src\App.ts(10,2)
      TS2345: Argument of type 'typeof App' is not assignable to parameter of type 'VueClass<Vue>'.
  Type 'typeof App' is not assignable to type 'new (...args: any[]) => Vue'.
    Type 'App' is not assignable to type 'Vue'.
      Types of property '$options' are incompatible.
        Type 'ComponentOptions<App, DefaultData<App>, DefaultMethods<App>, DefaultComputed, PropsDefinition<Rec...' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.
          Type 'App' is not assignable to type 'Vue'.

**Comment by qdot** [comment]
Well, um, I just realized that I hadn't actually posted the URL here on the project. :)

So, are you planning on adding to or changing the project? You don't need to install node and compile everything yourself unless you're planning on developing. The latest version of the app is always available at:

https://buttplug.world/playground

**Comment by Vermintin** [comment]
I started developping websocket server with Noble and bluetooth a few weeks ago for my personnal use, but your project is far more complete. Indeed i intend to develop a few `projects` for myselff  :), (relying on yours).
I am reviewing your code and It would be my pleasure to contribute if i can as i currently have free time.

**Comment by qdot** [comment]
BTW, we've got a node websocket server in active development at https://github.com/metafetish/buttplug-js-websocket-server. It integrates noble, so it can actually talk ble on mac/linux/win7. We're planning to use it for Win7 support soon.
