### ISSUE TITLE
Please remove Matomo tracking and remote resources (Google fonts)

### ISSUE THREAD

**Issue by kovacselemerand** [metafetish/buttplug-playground#54]
I noticed the Matomo tracking in the source code. This kind of application is the kind tracking is the very least acceptable in. When the webapp is run locally, it should operate offline and shouldn't connect to any server whatsoever. As far as I can tell, the tracking is not very intrusive: it just logs that you've used the app; however, it's also inappropriate because the URL of the public instance is hardcoded in it, so it logs it as if you accessed the public instance even if it's actually a local one (and _of course_ one's not going to use an online instance for something like this). As such, it shouldn't be part of the source code published for the purpose of running your own local server, even if some minimal logging is done in the public instance. Please remove it.

When run locally, the webapp also shouldn't load any resource from a remote server: it currently loads https://fonts.googleapis.com/icon?family=Material+Icons, a stylesheet that in turn loads a font. It's unfortunately popular to load resources like this, which in turn allow companies like Google track usage, but at least for an application of this kind they should be packaged into the app instead.

**Comment by qdot** [comment]
This app is unmaintained.
